// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: streamd/v1/replication.proto

package streamdv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplicationService_Negotiate_FullMethodName     = "/streamd.v1.ReplicationService/Negotiate"
	ReplicationService_Append_FullMethodName        = "/streamd.v1.ReplicationService/Append"
	ReplicationService_Barrier_FullMethodName       = "/streamd.v1.ReplicationService/Barrier"
	ReplicationService_AdvanceCommit_FullMethodName = "/streamd.v1.ReplicationService/AdvanceCommit"
)

// ReplicationServiceClient is the client API for ReplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReplicationService is an internal, mTLS-authenticated node-to-node API.
// Public clients must never be authorized to call it.
type ReplicationServiceClient interface {
	Negotiate(ctx context.Context, in *ReplicationServiceNegotiateRequest, opts ...grpc.CallOption) (*ReplicationServiceNegotiateResponse, error)
	Append(ctx context.Context, in *ReplicationServiceAppendRequest, opts ...grpc.CallOption) (*ReplicationServiceAppendResponse, error)
	Barrier(ctx context.Context, in *ReplicationServiceBarrierRequest, opts ...grpc.CallOption) (*ReplicationServiceBarrierResponse, error)
	AdvanceCommit(ctx context.Context, in *ReplicationServiceAdvanceCommitRequest, opts ...grpc.CallOption) (*ReplicationServiceAdvanceCommitResponse, error)
}

type replicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationServiceClient(cc grpc.ClientConnInterface) ReplicationServiceClient {
	return &replicationServiceClient{cc}
}

func (c *replicationServiceClient) Negotiate(ctx context.Context, in *ReplicationServiceNegotiateRequest, opts ...grpc.CallOption) (*ReplicationServiceNegotiateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicationServiceNegotiateResponse)
	err := c.cc.Invoke(ctx, ReplicationService_Negotiate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) Append(ctx context.Context, in *ReplicationServiceAppendRequest, opts ...grpc.CallOption) (*ReplicationServiceAppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicationServiceAppendResponse)
	err := c.cc.Invoke(ctx, ReplicationService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) Barrier(ctx context.Context, in *ReplicationServiceBarrierRequest, opts ...grpc.CallOption) (*ReplicationServiceBarrierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicationServiceBarrierResponse)
	err := c.cc.Invoke(ctx, ReplicationService_Barrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicationServiceClient) AdvanceCommit(ctx context.Context, in *ReplicationServiceAdvanceCommitRequest, opts ...grpc.CallOption) (*ReplicationServiceAdvanceCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicationServiceAdvanceCommitResponse)
	err := c.cc.Invoke(ctx, ReplicationService_AdvanceCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServiceServer is the server API for ReplicationService service.
// All implementations must embed UnimplementedReplicationServiceServer
// for forward compatibility.
//
// ReplicationService is an internal, mTLS-authenticated node-to-node API.
// Public clients must never be authorized to call it.
type ReplicationServiceServer interface {
	Negotiate(context.Context, *ReplicationServiceNegotiateRequest) (*ReplicationServiceNegotiateResponse, error)
	Append(context.Context, *ReplicationServiceAppendRequest) (*ReplicationServiceAppendResponse, error)
	Barrier(context.Context, *ReplicationServiceBarrierRequest) (*ReplicationServiceBarrierResponse, error)
	AdvanceCommit(context.Context, *ReplicationServiceAdvanceCommitRequest) (*ReplicationServiceAdvanceCommitResponse, error)
	mustEmbedUnimplementedReplicationServiceServer()
}

// UnimplementedReplicationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicationServiceServer struct{}

func (UnimplementedReplicationServiceServer) Negotiate(context.Context, *ReplicationServiceNegotiateRequest) (*ReplicationServiceNegotiateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Negotiate not implemented")
}
func (UnimplementedReplicationServiceServer) Append(context.Context, *ReplicationServiceAppendRequest) (*ReplicationServiceAppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedReplicationServiceServer) Barrier(context.Context, *ReplicationServiceBarrierRequest) (*ReplicationServiceBarrierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Barrier not implemented")
}
func (UnimplementedReplicationServiceServer) AdvanceCommit(context.Context, *ReplicationServiceAdvanceCommitRequest) (*ReplicationServiceAdvanceCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvanceCommit not implemented")
}
func (UnimplementedReplicationServiceServer) mustEmbedUnimplementedReplicationServiceServer() {}
func (UnimplementedReplicationServiceServer) testEmbeddedByValue()                            {}

// UnsafeReplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServiceServer will
// result in compilation errors.
type UnsafeReplicationServiceServer interface {
	mustEmbedUnimplementedReplicationServiceServer()
}

func RegisterReplicationServiceServer(s grpc.ServiceRegistrar, srv ReplicationServiceServer) {
	// If the following call panics, it indicates UnimplementedReplicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplicationService_ServiceDesc, srv)
}

func _ReplicationService_Negotiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationServiceNegotiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).Negotiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_Negotiate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).Negotiate(ctx, req.(*ReplicationServiceNegotiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationServiceAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).Append(ctx, req.(*ReplicationServiceAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_Barrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationServiceBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).Barrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_Barrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).Barrier(ctx, req.(*ReplicationServiceBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationService_AdvanceCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationServiceAdvanceCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).AdvanceCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_AdvanceCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).AdvanceCommit(ctx, req.(*ReplicationServiceAdvanceCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicationService_ServiceDesc is the grpc.ServiceDesc for ReplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streamd.v1.ReplicationService",
	HandlerType: (*ReplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Negotiate",
			Handler:    _ReplicationService_Negotiate_Handler,
		},
		{
			MethodName: "Append",
			Handler:    _ReplicationService_Append_Handler,
		},
		{
			MethodName: "Barrier",
			Handler:    _ReplicationService_Barrier_Handler,
		},
		{
			MethodName: "AdvanceCommit",
			Handler:    _ReplicationService_AdvanceCommit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "streamd/v1/replication.proto",
}
