// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: streamd/v1/replication.proto

package streamdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicationPlanMode int32

const (
	ReplicationPlanMode_REPLICATION_PLAN_MODE_UNSPECIFIED ReplicationPlanMode = 0
	ReplicationPlanMode_REPLICATION_PLAN_MODE_INCREMENTAL ReplicationPlanMode = 1
	ReplicationPlanMode_REPLICATION_PLAN_MODE_SNAPSHOT    ReplicationPlanMode = 2
)

// Enum value maps for ReplicationPlanMode.
var (
	ReplicationPlanMode_name = map[int32]string{
		0: "REPLICATION_PLAN_MODE_UNSPECIFIED",
		1: "REPLICATION_PLAN_MODE_INCREMENTAL",
		2: "REPLICATION_PLAN_MODE_SNAPSHOT",
	}
	ReplicationPlanMode_value = map[string]int32{
		"REPLICATION_PLAN_MODE_UNSPECIFIED": 0,
		"REPLICATION_PLAN_MODE_INCREMENTAL": 1,
		"REPLICATION_PLAN_MODE_SNAPSHOT":    2,
	}
)

func (x ReplicationPlanMode) Enum() *ReplicationPlanMode {
	p := new(ReplicationPlanMode)
	*p = x
	return p
}

func (x ReplicationPlanMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicationPlanMode) Descriptor() protoreflect.EnumDescriptor {
	return file_streamd_v1_replication_proto_enumTypes[0].Descriptor()
}

func (ReplicationPlanMode) Type() protoreflect.EnumType {
	return &file_streamd_v1_replication_proto_enumTypes[0]
}

func (x ReplicationPlanMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicationPlanMode.Descriptor instead.
func (ReplicationPlanMode) EnumDescriptor() ([]byte, []int) {
	return file_streamd_v1_replication_proto_rawDescGZIP(), []int{0}
}

type ReplicationPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	EntryId       uint64                 `protobuf:"varint,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Crc32C        uint32                 `protobuf:"fixed32,3,opt,name=crc32c,proto3" json:"crc32c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationPosition) Reset() {
	*x = ReplicationPosition{}
	mi := &file_streamd_v1_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationPosition) ProtoMessage() {}

func (x *ReplicationPosition) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationPosition.ProtoReflect.Descriptor instead.
func (*ReplicationPosition) Descriptor() ([]byte, []int) {
	return file_streamd_v1_replication_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicationPosition) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ReplicationPosition) GetEntryId() uint64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *ReplicationPosition) GetCrc32C() uint32 {
	if x != nil {
		return x.Crc32C
	}
	return 0
}

type ReplicationServiceNegotiateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion     uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	GroupId             []byte                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NodeId              []byte                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	KnownTerm           uint64                 `protobuf:"varint,4,opt,name=known_term,json=knownTerm,proto3" json:"known_term,omitempty"`
	InstalledSnapshotId []byte                 `protobuf:"bytes,5,opt,name=installed_snapshot_id,json=installedSnapshotId,proto3" json:"installed_snapshot_id,omitempty"`
	Snapshot            *ReplicationPosition   `protobuf:"bytes,6,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	LastAppended        *ReplicationPosition   `protobuf:"bytes,7,opt,name=last_appended,json=lastAppended,proto3" json:"last_appended,omitempty"`
	LocalDurable        *ReplicationPosition   `protobuf:"bytes,8,opt,name=local_durable,json=localDurable,proto3" json:"local_durable,omitempty"`
	Committed           *ReplicationPosition   `protobuf:"bytes,9,opt,name=committed,proto3" json:"committed,omitempty"`
	Applied             *ReplicationPosition   `protobuf:"bytes,10,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReplicationServiceNegotiateRequest) Reset() {
	*x = ReplicationServiceNegotiateRequest{}
	mi := &file_streamd_v1_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationServiceNegotiateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceNegotiateRequest) ProtoMessage() {}

func (x *ReplicationServiceNegotiateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceNegotiateRequest.ProtoReflect.Descriptor instead.
func (*ReplicationServiceNegotiateRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_replication_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicationServiceNegotiateRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ReplicationServiceNegotiateRequest) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *ReplicationServiceNegotiateRequest) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *ReplicationServiceNegotiateRequest) GetKnownTerm() uint64 {
	if x != nil {
		return x.KnownTerm
	}
	return 0
}

func (x *ReplicationServiceNegotiateRequest) GetInstalledSnapshotId() []byte {
	if x != nil {
		return x.InstalledSnapshotId
	}
	return nil
}

func (x *ReplicationServiceNegotiateRequest) GetSnapshot() *ReplicationPosition {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ReplicationServiceNegotiateRequest) GetLastAppended() *ReplicationPosition {
	if x != nil {
		return x.LastAppended
	}
	return nil
}

func (x *ReplicationServiceNegotiateRequest) GetLocalDurable() *ReplicationPosition {
	if x != nil {
		return x.LocalDurable
	}
	return nil
}

func (x *ReplicationServiceNegotiateRequest) GetCommitted() *ReplicationPosition {
	if x != nil {
		return x.Committed
	}
	return nil
}

func (x *ReplicationServiceNegotiateRequest) GetApplied() *ReplicationPosition {
	if x != nil {
		return x.Applied
	}
	return nil
}

type ReplicationServiceNegotiateResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion    uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Term               uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId           []byte                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Mode               ReplicationPlanMode    `protobuf:"varint,4,opt,name=mode,proto3,enum=streamd.v1.ReplicationPlanMode" json:"mode,omitempty"`
	StartEntryId       uint64                 `protobuf:"varint,5,opt,name=start_entry_id,json=startEntryId,proto3" json:"start_entry_id,omitempty"`
	SnapshotId         []byte                 `protobuf:"bytes,6,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Checkpoint         *ReplicationPosition   `protobuf:"bytes,7,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	EarliestWalEntryId uint64                 `protobuf:"varint,8,opt,name=earliest_wal_entry_id,json=earliestWalEntryId,proto3" json:"earliest_wal_entry_id,omitempty"`
	Committed          *ReplicationPosition   `protobuf:"bytes,9,opt,name=committed,proto3" json:"committed,omitempty"`
	GroupId            []byte                 `protobuf:"bytes,10,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReplicationServiceNegotiateResponse) Reset() {
	*x = ReplicationServiceNegotiateResponse{}
	mi := &file_streamd_v1_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationServiceNegotiateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceNegotiateResponse) ProtoMessage() {}

func (x *ReplicationServiceNegotiateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceNegotiateResponse.ProtoReflect.Descriptor instead.
func (*ReplicationServiceNegotiateResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_replication_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicationServiceNegotiateResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ReplicationServiceNegotiateResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ReplicationServiceNegotiateResponse) GetLeaderId() []byte {
	if x != nil {
		return x.LeaderId
	}
	return nil
}

func (x *ReplicationServiceNegotiateResponse) GetMode() ReplicationPlanMode {
	if x != nil {
		return x.Mode
	}
	return ReplicationPlanMode_REPLICATION_PLAN_MODE_UNSPECIFIED
}

func (x *ReplicationServiceNegotiateResponse) GetStartEntryId() uint64 {
	if x != nil {
		return x.StartEntryId
	}
	return 0
}

func (x *ReplicationServiceNegotiateResponse) GetSnapshotId() []byte {
	if x != nil {
		return x.SnapshotId
	}
	return nil
}

func (x *ReplicationServiceNegotiateResponse) GetCheckpoint() *ReplicationPosition {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *ReplicationServiceNegotiateResponse) GetEarliestWalEntryId() uint64 {
	if x != nil {
		return x.EarliestWalEntryId
	}
	return 0
}

func (x *ReplicationServiceNegotiateResponse) GetCommitted() *ReplicationPosition {
	if x != nil {
		return x.Committed
	}
	return nil
}

func (x *ReplicationServiceNegotiateResponse) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

type ReplicationServiceAppendRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	GroupId         []byte                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Term            uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId        []byte                 `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Previous        *ReplicationPosition   `protobuf:"bytes,5,opt,name=previous,proto3" json:"previous,omitempty"`
	Entries         [][]byte               `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicationServiceAppendRequest) Reset() {
	*x = ReplicationServiceAppendRequest{}
	mi := &file_streamd_v1_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationServiceAppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceAppendRequest) ProtoMessage() {}

func (x *ReplicationServiceAppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceAppendRequest.ProtoReflect.Descriptor instead.
func (*ReplicationServiceAppendRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_replication_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicationServiceAppendRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ReplicationServiceAppendRequest) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *ReplicationServiceAppendRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ReplicationServiceAppendRequest) GetLeaderId() []byte {
	if x != nil {
		return x.LeaderId
	}
	return nil
}

func (x *ReplicationServiceAppendRequest) GetPrevious() *ReplicationPosition {
	if x != nil {
		return x.Previous
	}
	return nil
}

func (x *ReplicationServiceAppendRequest) GetEntries() [][]byte {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReplicationServiceAppendResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	GroupId         []byte                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NodeId          []byte                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Term            uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicationServiceAppendResponse) Reset() {
	*x = ReplicationServiceAppendResponse{}
	mi := &file_streamd_v1_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationServiceAppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceAppendResponse) ProtoMessage() {}

func (x *ReplicationServiceAppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceAppendResponse.ProtoReflect.Descriptor instead.
func (*ReplicationServiceAppendResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_replication_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicationServiceAppendResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ReplicationServiceAppendResponse) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *ReplicationServiceAppendResponse) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *ReplicationServiceAppendResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type ReplicationServiceBarrierRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	GroupId         []byte                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Term            uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId        []byte                 `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	ThroughEntryId  uint64                 `protobuf:"varint,5,opt,name=through_entry_id,json=throughEntryId,proto3" json:"through_entry_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicationServiceBarrierRequest) Reset() {
	*x = ReplicationServiceBarrierRequest{}
	mi := &file_streamd_v1_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationServiceBarrierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceBarrierRequest) ProtoMessage() {}

func (x *ReplicationServiceBarrierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceBarrierRequest.ProtoReflect.Descriptor instead.
func (*ReplicationServiceBarrierRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_replication_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicationServiceBarrierRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ReplicationServiceBarrierRequest) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *ReplicationServiceBarrierRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ReplicationServiceBarrierRequest) GetLeaderId() []byte {
	if x != nil {
		return x.LeaderId
	}
	return nil
}

func (x *ReplicationServiceBarrierRequest) GetThroughEntryId() uint64 {
	if x != nil {
		return x.ThroughEntryId
	}
	return 0
}

type ReplicationServiceBarrierResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Term            uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Durable         *ReplicationPosition   `protobuf:"bytes,2,opt,name=durable,proto3" json:"durable,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	GroupId         []byte                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NodeId          []byte                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicationServiceBarrierResponse) Reset() {
	*x = ReplicationServiceBarrierResponse{}
	mi := &file_streamd_v1_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationServiceBarrierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceBarrierResponse) ProtoMessage() {}

func (x *ReplicationServiceBarrierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceBarrierResponse.ProtoReflect.Descriptor instead.
func (*ReplicationServiceBarrierResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_replication_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicationServiceBarrierResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ReplicationServiceBarrierResponse) GetDurable() *ReplicationPosition {
	if x != nil {
		return x.Durable
	}
	return nil
}

func (x *ReplicationServiceBarrierResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ReplicationServiceBarrierResponse) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *ReplicationServiceBarrierResponse) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

type ReplicationServiceAdvanceCommitRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	GroupId         []byte                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Term            uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId        []byte                 `protobuf:"bytes,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommitEntryId   uint64                 `protobuf:"varint,5,opt,name=commit_entry_id,json=commitEntryId,proto3" json:"commit_entry_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicationServiceAdvanceCommitRequest) Reset() {
	*x = ReplicationServiceAdvanceCommitRequest{}
	mi := &file_streamd_v1_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationServiceAdvanceCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceAdvanceCommitRequest) ProtoMessage() {}

func (x *ReplicationServiceAdvanceCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceAdvanceCommitRequest.ProtoReflect.Descriptor instead.
func (*ReplicationServiceAdvanceCommitRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_replication_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicationServiceAdvanceCommitRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ReplicationServiceAdvanceCommitRequest) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *ReplicationServiceAdvanceCommitRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ReplicationServiceAdvanceCommitRequest) GetLeaderId() []byte {
	if x != nil {
		return x.LeaderId
	}
	return nil
}

func (x *ReplicationServiceAdvanceCommitRequest) GetCommitEntryId() uint64 {
	if x != nil {
		return x.CommitEntryId
	}
	return 0
}

type ReplicationServiceAdvanceCommitResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	GroupId         []byte                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NodeId          []byte                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Term            uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplicationServiceAdvanceCommitResponse) Reset() {
	*x = ReplicationServiceAdvanceCommitResponse{}
	mi := &file_streamd_v1_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationServiceAdvanceCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationServiceAdvanceCommitResponse) ProtoMessage() {}

func (x *ReplicationServiceAdvanceCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationServiceAdvanceCommitResponse.ProtoReflect.Descriptor instead.
func (*ReplicationServiceAdvanceCommitResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_replication_proto_rawDescGZIP(), []int{8}
}

func (x *ReplicationServiceAdvanceCommitResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ReplicationServiceAdvanceCommitResponse) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *ReplicationServiceAdvanceCommitResponse) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *ReplicationServiceAdvanceCommitResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

var File_streamd_v1_replication_proto protoreflect.FileDescriptor

const file_streamd_v1_replication_proto_rawDesc = "" +
	"\n" +
	"\x1cstreamd/v1/replication.proto\x12\n" +
	"streamd.v1\"^\n" +
	"\x13ReplicationPosition\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\x04R\aentryId\x12\x16\n" +
	"\x06crc32c\x18\x03 \x01(\aR\x06crc32c\"\x99\x04\n" +
	"\"ReplicationServiceNegotiateRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\fR\agroupId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\fR\x06nodeId\x12\x1d\n" +
	"\n" +
	"known_term\x18\x04 \x01(\x04R\tknownTerm\x122\n" +
	"\x15installed_snapshot_id\x18\x05 \x01(\fR\x13installedSnapshotId\x12;\n" +
	"\bsnapshot\x18\x06 \x01(\v2\x1f.streamd.v1.ReplicationPositionR\bsnapshot\x12D\n" +
	"\rlast_appended\x18\a \x01(\v2\x1f.streamd.v1.ReplicationPositionR\flastAppended\x12D\n" +
	"\rlocal_durable\x18\b \x01(\v2\x1f.streamd.v1.ReplicationPositionR\flocalDurable\x12=\n" +
	"\tcommitted\x18\t \x01(\v2\x1f.streamd.v1.ReplicationPositionR\tcommitted\x129\n" +
	"\aapplied\x18\n" +
	" \x01(\v2\x1f.streamd.v1.ReplicationPositionR\aapplied\"\xcb\x03\n" +
	"#ReplicationServiceNegotiateResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\fR\bleaderId\x123\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1f.streamd.v1.ReplicationPlanModeR\x04mode\x12$\n" +
	"\x0estart_entry_id\x18\x05 \x01(\x04R\fstartEntryId\x12\x1f\n" +
	"\vsnapshot_id\x18\x06 \x01(\fR\n" +
	"snapshotId\x12?\n" +
	"\n" +
	"checkpoint\x18\a \x01(\v2\x1f.streamd.v1.ReplicationPositionR\n" +
	"checkpoint\x121\n" +
	"\x15earliest_wal_entry_id\x18\b \x01(\x04R\x12earliestWalEntryId\x12=\n" +
	"\tcommitted\x18\t \x01(\v2\x1f.streamd.v1.ReplicationPositionR\tcommitted\x12\x19\n" +
	"\bgroup_id\x18\n" +
	" \x01(\fR\agroupId\"\xef\x01\n" +
	"\x1fReplicationServiceAppendRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\fR\agroupId\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\fR\bleaderId\x12;\n" +
	"\bprevious\x18\x05 \x01(\v2\x1f.streamd.v1.ReplicationPositionR\bprevious\x12\x18\n" +
	"\aentries\x18\x06 \x03(\fR\aentries\"\x95\x01\n" +
	" ReplicationServiceAppendResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\fR\agroupId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\fR\x06nodeId\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\"\xc3\x01\n" +
	" ReplicationServiceBarrierRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\fR\agroupId\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\fR\bleaderId\x12(\n" +
	"\x10through_entry_id\x18\x05 \x01(\x04R\x0ethroughEntryId\"\xd1\x01\n" +
	"!ReplicationServiceBarrierResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x129\n" +
	"\adurable\x18\x02 \x01(\v2\x1f.streamd.v1.ReplicationPositionR\adurable\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\fR\agroupId\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\fR\x06nodeId\"\xc7\x01\n" +
	"&ReplicationServiceAdvanceCommitRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\fR\agroupId\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\fR\bleaderId\x12&\n" +
	"\x0fcommit_entry_id\x18\x05 \x01(\x04R\rcommitEntryId\"\x9c\x01\n" +
	"'ReplicationServiceAdvanceCommitResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\fR\agroupId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\fR\x06nodeId\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term*\x87\x01\n" +
	"\x13ReplicationPlanMode\x12%\n" +
	"!REPLICATION_PLAN_MODE_UNSPECIFIED\x10\x00\x12%\n" +
	"!REPLICATION_PLAN_MODE_INCREMENTAL\x10\x01\x12\"\n" +
	"\x1eREPLICATION_PLAN_MODE_SNAPSHOT\x10\x022\xc9\x03\n" +
	"\x12ReplicationService\x12l\n" +
	"\tNegotiate\x12..streamd.v1.ReplicationServiceNegotiateRequest\x1a/.streamd.v1.ReplicationServiceNegotiateResponse\x12c\n" +
	"\x06Append\x12+.streamd.v1.ReplicationServiceAppendRequest\x1a,.streamd.v1.ReplicationServiceAppendResponse\x12f\n" +
	"\aBarrier\x12,.streamd.v1.ReplicationServiceBarrierRequest\x1a-.streamd.v1.ReplicationServiceBarrierResponse\x12x\n" +
	"\rAdvanceCommit\x122.streamd.v1.ReplicationServiceAdvanceCommitRequest\x1a3.streamd.v1.ReplicationServiceAdvanceCommitResponseB2Z0github.com/akzj/streamd/api/streamd/v1;streamdv1b\x06proto3"

var (
	file_streamd_v1_replication_proto_rawDescOnce sync.Once
	file_streamd_v1_replication_proto_rawDescData []byte
)

func file_streamd_v1_replication_proto_rawDescGZIP() []byte {
	file_streamd_v1_replication_proto_rawDescOnce.Do(func() {
		file_streamd_v1_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamd_v1_replication_proto_rawDesc), len(file_streamd_v1_replication_proto_rawDesc)))
	})
	return file_streamd_v1_replication_proto_rawDescData
}

var file_streamd_v1_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streamd_v1_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_streamd_v1_replication_proto_goTypes = []any{
	(ReplicationPlanMode)(0),                        // 0: streamd.v1.ReplicationPlanMode
	(*ReplicationPosition)(nil),                     // 1: streamd.v1.ReplicationPosition
	(*ReplicationServiceNegotiateRequest)(nil),      // 2: streamd.v1.ReplicationServiceNegotiateRequest
	(*ReplicationServiceNegotiateResponse)(nil),     // 3: streamd.v1.ReplicationServiceNegotiateResponse
	(*ReplicationServiceAppendRequest)(nil),         // 4: streamd.v1.ReplicationServiceAppendRequest
	(*ReplicationServiceAppendResponse)(nil),        // 5: streamd.v1.ReplicationServiceAppendResponse
	(*ReplicationServiceBarrierRequest)(nil),        // 6: streamd.v1.ReplicationServiceBarrierRequest
	(*ReplicationServiceBarrierResponse)(nil),       // 7: streamd.v1.ReplicationServiceBarrierResponse
	(*ReplicationServiceAdvanceCommitRequest)(nil),  // 8: streamd.v1.ReplicationServiceAdvanceCommitRequest
	(*ReplicationServiceAdvanceCommitResponse)(nil), // 9: streamd.v1.ReplicationServiceAdvanceCommitResponse
}
var file_streamd_v1_replication_proto_depIdxs = []int32{
	1,  // 0: streamd.v1.ReplicationServiceNegotiateRequest.snapshot:type_name -> streamd.v1.ReplicationPosition
	1,  // 1: streamd.v1.ReplicationServiceNegotiateRequest.last_appended:type_name -> streamd.v1.ReplicationPosition
	1,  // 2: streamd.v1.ReplicationServiceNegotiateRequest.local_durable:type_name -> streamd.v1.ReplicationPosition
	1,  // 3: streamd.v1.ReplicationServiceNegotiateRequest.committed:type_name -> streamd.v1.ReplicationPosition
	1,  // 4: streamd.v1.ReplicationServiceNegotiateRequest.applied:type_name -> streamd.v1.ReplicationPosition
	0,  // 5: streamd.v1.ReplicationServiceNegotiateResponse.mode:type_name -> streamd.v1.ReplicationPlanMode
	1,  // 6: streamd.v1.ReplicationServiceNegotiateResponse.checkpoint:type_name -> streamd.v1.ReplicationPosition
	1,  // 7: streamd.v1.ReplicationServiceNegotiateResponse.committed:type_name -> streamd.v1.ReplicationPosition
	1,  // 8: streamd.v1.ReplicationServiceAppendRequest.previous:type_name -> streamd.v1.ReplicationPosition
	1,  // 9: streamd.v1.ReplicationServiceBarrierResponse.durable:type_name -> streamd.v1.ReplicationPosition
	2,  // 10: streamd.v1.ReplicationService.Negotiate:input_type -> streamd.v1.ReplicationServiceNegotiateRequest
	4,  // 11: streamd.v1.ReplicationService.Append:input_type -> streamd.v1.ReplicationServiceAppendRequest
	6,  // 12: streamd.v1.ReplicationService.Barrier:input_type -> streamd.v1.ReplicationServiceBarrierRequest
	8,  // 13: streamd.v1.ReplicationService.AdvanceCommit:input_type -> streamd.v1.ReplicationServiceAdvanceCommitRequest
	3,  // 14: streamd.v1.ReplicationService.Negotiate:output_type -> streamd.v1.ReplicationServiceNegotiateResponse
	5,  // 15: streamd.v1.ReplicationService.Append:output_type -> streamd.v1.ReplicationServiceAppendResponse
	7,  // 16: streamd.v1.ReplicationService.Barrier:output_type -> streamd.v1.ReplicationServiceBarrierResponse
	9,  // 17: streamd.v1.ReplicationService.AdvanceCommit:output_type -> streamd.v1.ReplicationServiceAdvanceCommitResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_streamd_v1_replication_proto_init() }
func file_streamd_v1_replication_proto_init() {
	if File_streamd_v1_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamd_v1_replication_proto_rawDesc), len(file_streamd_v1_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streamd_v1_replication_proto_goTypes,
		DependencyIndexes: file_streamd_v1_replication_proto_depIdxs,
		EnumInfos:         file_streamd_v1_replication_proto_enumTypes,
		MessageInfos:      file_streamd_v1_replication_proto_msgTypes,
	}.Build()
	File_streamd_v1_replication_proto = out.File
	file_streamd_v1_replication_proto_goTypes = nil
	file_streamd_v1_replication_proto_depIdxs = nil
}
