// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: streamd/v1/streamd.proto

package streamdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Durability int32

const (
	Durability_DURABILITY_UNSPECIFIED         Durability = 0
	Durability_DURABILITY_SINGLE_SYNC         Durability = 1
	Durability_DURABILITY_REPLICATED_STRICT   Durability = 2
	Durability_DURABILITY_DEGRADED_LOCAL_ONLY Durability = 3
)

// Enum value maps for Durability.
var (
	Durability_name = map[int32]string{
		0: "DURABILITY_UNSPECIFIED",
		1: "DURABILITY_SINGLE_SYNC",
		2: "DURABILITY_REPLICATED_STRICT",
		3: "DURABILITY_DEGRADED_LOCAL_ONLY",
	}
	Durability_value = map[string]int32{
		"DURABILITY_UNSPECIFIED":         0,
		"DURABILITY_SINGLE_SYNC":         1,
		"DURABILITY_REPLICATED_STRICT":   2,
		"DURABILITY_DEGRADED_LOCAL_ONLY": 3,
	}
)

func (x Durability) Enum() *Durability {
	p := new(Durability)
	*p = x
	return p
}

func (x Durability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Durability) Descriptor() protoreflect.EnumDescriptor {
	return file_streamd_v1_streamd_proto_enumTypes[0].Descriptor()
}

func (Durability) Type() protoreflect.EnumType {
	return &file_streamd_v1_streamd_proto_enumTypes[0]
}

func (x Durability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Durability.Descriptor instead.
func (Durability) EnumDescriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{0}
}

type ResolveTimeMode int32

const (
	ResolveTimeMode_RESOLVE_TIME_MODE_UNSPECIFIED  ResolveTimeMode = 0
	ResolveTimeMode_RESOLVE_TIME_MODE_AT_OR_AFTER  ResolveTimeMode = 1
	ResolveTimeMode_RESOLVE_TIME_MODE_AT_OR_BEFORE ResolveTimeMode = 2
)

// Enum value maps for ResolveTimeMode.
var (
	ResolveTimeMode_name = map[int32]string{
		0: "RESOLVE_TIME_MODE_UNSPECIFIED",
		1: "RESOLVE_TIME_MODE_AT_OR_AFTER",
		2: "RESOLVE_TIME_MODE_AT_OR_BEFORE",
	}
	ResolveTimeMode_value = map[string]int32{
		"RESOLVE_TIME_MODE_UNSPECIFIED":  0,
		"RESOLVE_TIME_MODE_AT_OR_AFTER":  1,
		"RESOLVE_TIME_MODE_AT_OR_BEFORE": 2,
	}
)

func (x ResolveTimeMode) Enum() *ResolveTimeMode {
	p := new(ResolveTimeMode)
	*p = x
	return p
}

func (x ResolveTimeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolveTimeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_streamd_v1_streamd_proto_enumTypes[1].Descriptor()
}

func (ResolveTimeMode) Type() protoreflect.EnumType {
	return &file_streamd_v1_streamd_proto_enumTypes[1]
}

func (x ResolveTimeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolveTimeMode.Descriptor instead.
func (ResolveTimeMode) EnumDescriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{1}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_STARTING    HealthStatus = 1
	HealthStatus_HEALTH_STATUS_READY_READ  HealthStatus = 2
	HealthStatus_HEALTH_STATUS_READY_WRITE HealthStatus = 3
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 4
	HealthStatus_HEALTH_STATUS_FAILED      HealthStatus = 5
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_STARTING",
		2: "HEALTH_STATUS_READY_READ",
		3: "HEALTH_STATUS_READY_WRITE",
		4: "HEALTH_STATUS_DEGRADED",
		5: "HEALTH_STATUS_FAILED",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_STARTING":    1,
		"HEALTH_STATUS_READY_READ":  2,
		"HEALTH_STATUS_READY_WRITE": 3,
		"HEALTH_STATUS_DEGRADED":    4,
		"HEALTH_STATUS_FAILED":      5,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_streamd_v1_streamd_proto_enumTypes[2].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_streamd_v1_streamd_proto_enumTypes[2]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{2}
}

type NodeRole int32

const (
	NodeRole_NODE_ROLE_UNSPECIFIED NodeRole = 0
	NodeRole_NODE_ROLE_SINGLE      NodeRole = 1
	NodeRole_NODE_ROLE_PRIMARY     NodeRole = 2
	NodeRole_NODE_ROLE_STANDBY     NodeRole = 3
	NodeRole_NODE_ROLE_RECOVERING  NodeRole = 4
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "NODE_ROLE_UNSPECIFIED",
		1: "NODE_ROLE_SINGLE",
		2: "NODE_ROLE_PRIMARY",
		3: "NODE_ROLE_STANDBY",
		4: "NODE_ROLE_RECOVERING",
	}
	NodeRole_value = map[string]int32{
		"NODE_ROLE_UNSPECIFIED": 0,
		"NODE_ROLE_SINGLE":      1,
		"NODE_ROLE_PRIMARY":     2,
		"NODE_ROLE_STANDBY":     3,
		"NODE_ROLE_RECOVERING":  4,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_streamd_v1_streamd_proto_enumTypes[3].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_streamd_v1_streamd_proto_enumTypes[3]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{3}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED            ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT       ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHENTICATED        ErrorCode = 2
	ErrorCode_ERROR_CODE_PERMISSION_DENIED      ErrorCode = 3
	ErrorCode_ERROR_CODE_STREAM_NOT_FOUND       ErrorCode = 4
	ErrorCode_ERROR_CODE_SEQUENCE_AHEAD         ErrorCode = 5
	ErrorCode_ERROR_CODE_SEQUENCE_CONFLICT      ErrorCode = 6
	ErrorCode_ERROR_CODE_RECORD_TOO_LARGE       ErrorCode = 7
	ErrorCode_ERROR_CODE_RESOURCE_EXHAUSTED     ErrorCode = 8
	ErrorCode_ERROR_CODE_DURABILITY_UNAVAILABLE ErrorCode = 9
	ErrorCode_ERROR_CODE_NOT_LEADER             ErrorCode = 10
	ErrorCode_ERROR_CODE_REPLICA_UNAVAILABLE    ErrorCode = 11
	ErrorCode_ERROR_CODE_DEADLINE_EXCEEDED      ErrorCode = 12
	ErrorCode_ERROR_CODE_SLOW_CONSUMER          ErrorCode = 13
	ErrorCode_ERROR_CODE_DATA_LOSS              ErrorCode = 14
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_INVALID_ARGUMENT",
		2:  "ERROR_CODE_UNAUTHENTICATED",
		3:  "ERROR_CODE_PERMISSION_DENIED",
		4:  "ERROR_CODE_STREAM_NOT_FOUND",
		5:  "ERROR_CODE_SEQUENCE_AHEAD",
		6:  "ERROR_CODE_SEQUENCE_CONFLICT",
		7:  "ERROR_CODE_RECORD_TOO_LARGE",
		8:  "ERROR_CODE_RESOURCE_EXHAUSTED",
		9:  "ERROR_CODE_DURABILITY_UNAVAILABLE",
		10: "ERROR_CODE_NOT_LEADER",
		11: "ERROR_CODE_REPLICA_UNAVAILABLE",
		12: "ERROR_CODE_DEADLINE_EXCEEDED",
		13: "ERROR_CODE_SLOW_CONSUMER",
		14: "ERROR_CODE_DATA_LOSS",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":            0,
		"ERROR_CODE_INVALID_ARGUMENT":       1,
		"ERROR_CODE_UNAUTHENTICATED":        2,
		"ERROR_CODE_PERMISSION_DENIED":      3,
		"ERROR_CODE_STREAM_NOT_FOUND":       4,
		"ERROR_CODE_SEQUENCE_AHEAD":         5,
		"ERROR_CODE_SEQUENCE_CONFLICT":      6,
		"ERROR_CODE_RECORD_TOO_LARGE":       7,
		"ERROR_CODE_RESOURCE_EXHAUSTED":     8,
		"ERROR_CODE_DURABILITY_UNAVAILABLE": 9,
		"ERROR_CODE_NOT_LEADER":             10,
		"ERROR_CODE_REPLICA_UNAVAILABLE":    11,
		"ERROR_CODE_DEADLINE_EXCEEDED":      12,
		"ERROR_CODE_SLOW_CONSUMER":          13,
		"ERROR_CODE_DATA_LOSS":              14,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_streamd_v1_streamd_proto_enumTypes[4].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_streamd_v1_streamd_proto_enumTypes[4]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{4}
}

type StreamRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRef) Reset() {
	*x = StreamRef{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRef) ProtoMessage() {}

func (x *StreamRef) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRef.ProtoReflect.Descriptor instead.
func (*StreamRef) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StreamRef) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type InputRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string][]byte      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputRecord) Reset() {
	*x = InputRecord{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRecord) ProtoMessage() {}

func (x *InputRecord) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRecord.ProtoReflect.Descriptor instead.
func (*InputRecord) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{1}
}

func (x *InputRecord) GetHeaders() map[string][]byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InputRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StoredRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sequence       uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	RecordedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	RequestId      []byte                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Producer       string                 `protobuf:"bytes,4,opt,name=producer,proto3" json:"producer,omitempty"`
	Headers        map[string][]byte      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload        []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	StorageEntryId uint64                 `protobuf:"varint,7,opt,name=storage_entry_id,json=storageEntryId,proto3" json:"storage_entry_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoredRecord) Reset() {
	*x = StoredRecord{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredRecord) ProtoMessage() {}

func (x *StoredRecord) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredRecord.ProtoReflect.Descriptor instead.
func (*StoredRecord) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{2}
}

func (x *StoredRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StoredRecord) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

func (x *StoredRecord) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *StoredRecord) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *StoredRecord) GetHeaders() map[string][]byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *StoredRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StoredRecord) GetStorageEntryId() uint64 {
	if x != nil {
		return x.StorageEntryId
	}
	return 0
}

type AppendRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Stream             *StreamRef             `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	ExpectedSequence   uint64                 `protobuf:"varint,2,opt,name=expected_sequence,json=expectedSequence,proto3" json:"expected_sequence,omitempty"`
	RequestId          []byte                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Record             *InputRecord           `protobuf:"bytes,4,opt,name=record,proto3" json:"record,omitempty"`
	RequiredDurability Durability             `protobuf:"varint,5,opt,name=required_durability,json=requiredDurability,proto3,enum=streamd.v1.Durability" json:"required_durability,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{3}
}

func (x *AppendRequest) GetStream() *StreamRef {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *AppendRequest) GetExpectedSequence() uint64 {
	if x != nil {
		return x.ExpectedSequence
	}
	return 0
}

func (x *AppendRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *AppendRequest) GetRecord() *InputRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *AppendRequest) GetRequiredDurability() Durability {
	if x != nil {
		return x.RequiredDurability
	}
	return Durability_DURABILITY_UNSPECIFIED
}

type AppendResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sequence       uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	NextSequence   uint64                 `protobuf:"varint,2,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	RecordedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	StorageEntryId uint64                 `protobuf:"varint,4,opt,name=storage_entry_id,json=storageEntryId,proto3" json:"storage_entry_id,omitempty"`
	Deduplicated   bool                   `protobuf:"varint,5,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	Durability     Durability             `protobuf:"varint,6,opt,name=durability,proto3,enum=streamd.v1.Durability" json:"durability,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{4}
}

func (x *AppendResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AppendResponse) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *AppendResponse) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

func (x *AppendResponse) GetStorageEntryId() uint64 {
	if x != nil {
		return x.StorageEntryId
	}
	return 0
}

func (x *AppendResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

func (x *AppendResponse) GetDurability() Durability {
	if x != nil {
		return x.Durability
	}
	return Durability_DURABILITY_UNSPECIFIED
}

type AppendBatchRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Stream             *StreamRef             `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	ExpectedSequence   uint64                 `protobuf:"varint,2,opt,name=expected_sequence,json=expectedSequence,proto3" json:"expected_sequence,omitempty"`
	RequestId          []byte                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Records            []*InputRecord         `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	RequiredDurability Durability             `protobuf:"varint,5,opt,name=required_durability,json=requiredDurability,proto3,enum=streamd.v1.Durability" json:"required_durability,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AppendBatchRequest) Reset() {
	*x = AppendBatchRequest{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBatchRequest) ProtoMessage() {}

func (x *AppendBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBatchRequest.ProtoReflect.Descriptor instead.
func (*AppendBatchRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{5}
}

func (x *AppendBatchRequest) GetStream() *StreamRef {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *AppendBatchRequest) GetExpectedSequence() uint64 {
	if x != nil {
		return x.ExpectedSequence
	}
	return 0
}

func (x *AppendBatchRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *AppendBatchRequest) GetRecords() []*InputRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *AppendBatchRequest) GetRequiredDurability() Durability {
	if x != nil {
		return x.RequiredDurability
	}
	return Durability_DURABILITY_UNSPECIFIED
}

type AppendBatchResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FirstSequence       uint64                 `protobuf:"varint,1,opt,name=first_sequence,json=firstSequence,proto3" json:"first_sequence,omitempty"`
	NextSequence        uint64                 `protobuf:"varint,2,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	RecordCount         uint32                 `protobuf:"varint,3,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	FirstRecordedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_recorded_at,json=firstRecordedAt,proto3" json:"first_recorded_at,omitempty"`
	LastRecordedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_recorded_at,json=lastRecordedAt,proto3" json:"last_recorded_at,omitempty"`
	FirstStorageEntryId uint64                 `protobuf:"varint,6,opt,name=first_storage_entry_id,json=firstStorageEntryId,proto3" json:"first_storage_entry_id,omitempty"`
	LastStorageEntryId  uint64                 `protobuf:"varint,7,opt,name=last_storage_entry_id,json=lastStorageEntryId,proto3" json:"last_storage_entry_id,omitempty"`
	Deduplicated        bool                   `protobuf:"varint,8,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	Durability          Durability             `protobuf:"varint,9,opt,name=durability,proto3,enum=streamd.v1.Durability" json:"durability,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AppendBatchResponse) Reset() {
	*x = AppendBatchResponse{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBatchResponse) ProtoMessage() {}

func (x *AppendBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBatchResponse.ProtoReflect.Descriptor instead.
func (*AppendBatchResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{6}
}

func (x *AppendBatchResponse) GetFirstSequence() uint64 {
	if x != nil {
		return x.FirstSequence
	}
	return 0
}

func (x *AppendBatchResponse) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *AppendBatchResponse) GetRecordCount() uint32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *AppendBatchResponse) GetFirstRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstRecordedAt
	}
	return nil
}

func (x *AppendBatchResponse) GetLastRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRecordedAt
	}
	return nil
}

func (x *AppendBatchResponse) GetFirstStorageEntryId() uint64 {
	if x != nil {
		return x.FirstStorageEntryId
	}
	return 0
}

func (x *AppendBatchResponse) GetLastStorageEntryId() uint64 {
	if x != nil {
		return x.LastStorageEntryId
	}
	return 0
}

func (x *AppendBatchResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

func (x *AppendBatchResponse) GetDurability() Durability {
	if x != nil {
		return x.Durability
	}
	return Durability_DURABILITY_UNSPECIFIED
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamRef             `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	FromSequence  uint64                 `protobuf:"varint,2,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	MaxRecords    uint32                 `protobuf:"varint,3,opt,name=max_records,json=maxRecords,proto3" json:"max_records,omitempty"`
	MaxBytes      uint64                 `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{7}
}

func (x *ReadRequest) GetStream() *StreamRef {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *ReadRequest) GetFromSequence() uint64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

func (x *ReadRequest) GetMaxRecords() uint32 {
	if x != nil {
		return x.MaxRecords
	}
	return 0
}

func (x *ReadRequest) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type ReadResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Records             []*StoredRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextSequence        uint64                 `protobuf:"varint,2,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	CurrentNextSequence uint64                 `protobuf:"varint,3,opt,name=current_next_sequence,json=currentNextSequence,proto3" json:"current_next_sequence,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{8}
}

func (x *ReadResponse) GetRecords() []*StoredRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ReadResponse) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *ReadResponse) GetCurrentNextSequence() uint64 {
	if x != nil {
		return x.CurrentNextSequence
	}
	return 0
}

type SubscribeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Stream            *StreamRef             `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	FromSequence      uint64                 `protobuf:"varint,2,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	MaxBatchRecords   uint32                 `protobuf:"varint,3,opt,name=max_batch_records,json=maxBatchRecords,proto3" json:"max_batch_records,omitempty"`
	MaxBatchBytes     uint64                 `protobuf:"varint,4,opt,name=max_batch_bytes,json=maxBatchBytes,proto3" json:"max_batch_bytes,omitempty"`
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,5,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRequest) GetStream() *StreamRef {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *SubscribeRequest) GetFromSequence() uint64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

func (x *SubscribeRequest) GetMaxBatchRecords() uint32 {
	if x != nil {
		return x.MaxBatchRecords
	}
	return 0
}

func (x *SubscribeRequest) GetMaxBatchBytes() uint64 {
	if x != nil {
		return x.MaxBatchBytes
	}
	return 0
}

func (x *SubscribeRequest) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

type SubscribeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Records             []*StoredRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextSequence        uint64                 `protobuf:"varint,2,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	CurrentNextSequence uint64                 `protobuf:"varint,3,opt,name=current_next_sequence,json=currentNextSequence,proto3" json:"current_next_sequence,omitempty"`
	Heartbeat           bool                   `protobuf:"varint,4,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeResponse) GetRecords() []*StoredRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *SubscribeResponse) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *SubscribeResponse) GetCurrentNextSequence() uint64 {
	if x != nil {
		return x.CurrentNextSequence
	}
	return 0
}

func (x *SubscribeResponse) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

type ResolveTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamRef             `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	RecordedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	Mode          ResolveTimeMode        `protobuf:"varint,3,opt,name=mode,proto3,enum=streamd.v1.ResolveTimeMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTimeRequest) Reset() {
	*x = ResolveTimeRequest{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTimeRequest) ProtoMessage() {}

func (x *ResolveTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTimeRequest.ProtoReflect.Descriptor instead.
func (*ResolveTimeRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveTimeRequest) GetStream() *StreamRef {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *ResolveTimeRequest) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

func (x *ResolveTimeRequest) GetMode() ResolveTimeMode {
	if x != nil {
		return x.Mode
	}
	return ResolveTimeMode_RESOLVE_TIME_MODE_UNSPECIFIED
}

type ResolveTimeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Found            bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Sequence         uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ActualRecordedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=actual_recorded_at,json=actualRecordedAt,proto3" json:"actual_recorded_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveTimeResponse) Reset() {
	*x = ResolveTimeResponse{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTimeResponse) ProtoMessage() {}

func (x *ResolveTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTimeResponse.ProtoReflect.Descriptor instead.
func (*ResolveTimeResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveTimeResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResolveTimeResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ResolveTimeResponse) GetActualRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualRecordedAt
	}
	return nil
}

type InspectStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamRef             `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectStreamRequest) Reset() {
	*x = InspectStreamRequest{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectStreamRequest) ProtoMessage() {}

func (x *InspectStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectStreamRequest.ProtoReflect.Descriptor instead.
func (*InspectStreamRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{13}
}

func (x *InspectStreamRequest) GetStream() *StreamRef {
	if x != nil {
		return x.Stream
	}
	return nil
}

type InspectStreamResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Exists          bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	HeadSequence    uint64                 `protobuf:"varint,2,opt,name=head_sequence,json=headSequence,proto3" json:"head_sequence,omitempty"`
	NextSequence    uint64                 `protobuf:"varint,3,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	RecordCount     uint64                 `protobuf:"varint,4,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	FirstRecordedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_recorded_at,json=firstRecordedAt,proto3" json:"first_recorded_at,omitempty"`
	LastRecordedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_recorded_at,json=lastRecordedAt,proto3" json:"last_recorded_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InspectStreamResponse) Reset() {
	*x = InspectStreamResponse{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectStreamResponse) ProtoMessage() {}

func (x *InspectStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectStreamResponse.ProtoReflect.Descriptor instead.
func (*InspectStreamResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{14}
}

func (x *InspectStreamResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *InspectStreamResponse) GetHeadSequence() uint64 {
	if x != nil {
		return x.HeadSequence
	}
	return 0
}

func (x *InspectStreamResponse) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *InspectStreamResponse) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *InspectStreamResponse) GetFirstRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstRecordedAt
	}
	return nil
}

func (x *InspectStreamResponse) GetLastRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRecordedAt
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{15}
}

type HealthResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Status                HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=streamd.v1.HealthStatus" json:"status,omitempty"`
	Role                  NodeRole               `protobuf:"varint,2,opt,name=role,proto3,enum=streamd.v1.NodeRole" json:"role,omitempty"`
	Term                  *uint64                `protobuf:"varint,3,opt,name=term,proto3,oneof" json:"term,omitempty"`
	Durability            Durability             `protobuf:"varint,4,opt,name=durability,proto3,enum=streamd.v1.Durability" json:"durability,omitempty"`
	LocalDurableEntryId   *uint64                `protobuf:"varint,5,opt,name=local_durable_entry_id,json=localDurableEntryId,proto3,oneof" json:"local_durable_entry_id,omitempty"`
	CommitEntryId         *uint64                `protobuf:"varint,6,opt,name=commit_entry_id,json=commitEntryId,proto3,oneof" json:"commit_entry_id,omitempty"`
	AppliedEntryId        *uint64                `protobuf:"varint,7,opt,name=applied_entry_id,json=appliedEntryId,proto3,oneof" json:"applied_entry_id,omitempty"`
	ReplicationLagEntries *uint64                `protobuf:"varint,8,opt,name=replication_lag_entries,json=replicationLagEntries,proto3,oneof" json:"replication_lag_entries,omitempty"`
	Reasons               []string               `protobuf:"bytes,9,rep,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{16}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_NODE_ROLE_UNSPECIFIED
}

func (x *HealthResponse) GetTerm() uint64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

func (x *HealthResponse) GetDurability() Durability {
	if x != nil {
		return x.Durability
	}
	return Durability_DURABILITY_UNSPECIFIED
}

func (x *HealthResponse) GetLocalDurableEntryId() uint64 {
	if x != nil && x.LocalDurableEntryId != nil {
		return *x.LocalDurableEntryId
	}
	return 0
}

func (x *HealthResponse) GetCommitEntryId() uint64 {
	if x != nil && x.CommitEntryId != nil {
		return *x.CommitEntryId
	}
	return 0
}

func (x *HealthResponse) GetAppliedEntryId() uint64 {
	if x != nil && x.AppliedEntryId != nil {
		return *x.AppliedEntryId
	}
	return 0
}

func (x *HealthResponse) GetReplicationLagEntries() uint64 {
	if x != nil && x.ReplicationLagEntries != nil {
		return *x.ReplicationLagEntries
	}
	return 0
}

func (x *HealthResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

// StreamdError is attached to a gRPC status as an error detail.
type StreamdError struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Code                ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=streamd.v1.ErrorCode" json:"code,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable           bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	ResultUncertain     bool                   `protobuf:"varint,4,opt,name=result_uncertain,json=resultUncertain,proto3" json:"result_uncertain,omitempty"`
	CurrentNextSequence *uint64                `protobuf:"varint,5,opt,name=current_next_sequence,json=currentNextSequence,proto3,oneof" json:"current_next_sequence,omitempty"`
	LeaderHint          *string                `protobuf:"bytes,6,opt,name=leader_hint,json=leaderHint,proto3,oneof" json:"leader_hint,omitempty"`
	RequiredBytes       *uint64                `protobuf:"varint,7,opt,name=required_bytes,json=requiredBytes,proto3,oneof" json:"required_bytes,omitempty"`
	RequestId           []byte                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StreamdError) Reset() {
	*x = StreamdError{}
	mi := &file_streamd_v1_streamd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamdError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamdError) ProtoMessage() {}

func (x *StreamdError) ProtoReflect() protoreflect.Message {
	mi := &file_streamd_v1_streamd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamdError.ProtoReflect.Descriptor instead.
func (*StreamdError) Descriptor() ([]byte, []int) {
	return file_streamd_v1_streamd_proto_rawDescGZIP(), []int{17}
}

func (x *StreamdError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *StreamdError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamdError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *StreamdError) GetResultUncertain() bool {
	if x != nil {
		return x.ResultUncertain
	}
	return false
}

func (x *StreamdError) GetCurrentNextSequence() uint64 {
	if x != nil && x.CurrentNextSequence != nil {
		return *x.CurrentNextSequence
	}
	return 0
}

func (x *StreamdError) GetLeaderHint() string {
	if x != nil && x.LeaderHint != nil {
		return *x.LeaderHint
	}
	return ""
}

func (x *StreamdError) GetRequiredBytes() uint64 {
	if x != nil && x.RequiredBytes != nil {
		return *x.RequiredBytes
	}
	return 0
}

func (x *StreamdError) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

var File_streamd_v1_streamd_proto protoreflect.FileDescriptor

const file_streamd_v1_streamd_proto_rawDesc = "" +
	"\n" +
	"\x18streamd/v1/streamd.proto\x12\n" +
	"streamd.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\tStreamRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\"\xa3\x01\n" +
	"\vInputRecord\x12>\n" +
	"\aheaders\x18\x01 \x03(\v2$.streamd.v1.InputRecord.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xe3\x02\n" +
	"\fStoredRecord\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12;\n" +
	"\vrecorded_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\fR\trequestId\x12\x1a\n" +
	"\bproducer\x18\x04 \x01(\tR\bproducer\x12?\n" +
	"\aheaders\x18\x05 \x03(\v2%.streamd.v1.StoredRecord.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12(\n" +
	"\x10storage_entry_id\x18\a \x01(\x04R\x0estorageEntryId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x84\x02\n" +
	"\rAppendRequest\x12-\n" +
	"\x06stream\x18\x01 \x01(\v2\x15.streamd.v1.StreamRefR\x06stream\x12+\n" +
	"\x11expected_sequence\x18\x02 \x01(\x04R\x10expectedSequence\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\fR\trequestId\x12/\n" +
	"\x06record\x18\x04 \x01(\v2\x17.streamd.v1.InputRecordR\x06record\x12G\n" +
	"\x13required_durability\x18\x05 \x01(\x0e2\x16.streamd.v1.DurabilityR\x12requiredDurability\"\x94\x02\n" +
	"\x0eAppendResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12#\n" +
	"\rnext_sequence\x18\x02 \x01(\x04R\fnextSequence\x12;\n" +
	"\vrecorded_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\x12(\n" +
	"\x10storage_entry_id\x18\x04 \x01(\x04R\x0estorageEntryId\x12\"\n" +
	"\fdeduplicated\x18\x05 \x01(\bR\fdeduplicated\x126\n" +
	"\n" +
	"durability\x18\x06 \x01(\x0e2\x16.streamd.v1.DurabilityR\n" +
	"durability\"\x8b\x02\n" +
	"\x12AppendBatchRequest\x12-\n" +
	"\x06stream\x18\x01 \x01(\v2\x15.streamd.v1.StreamRefR\x06stream\x12+\n" +
	"\x11expected_sequence\x18\x02 \x01(\x04R\x10expectedSequence\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\fR\trequestId\x121\n" +
	"\arecords\x18\x04 \x03(\v2\x17.streamd.v1.InputRecordR\arecords\x12G\n" +
	"\x13required_durability\x18\x05 \x01(\x0e2\x16.streamd.v1.DurabilityR\x12requiredDurability\"\xd6\x03\n" +
	"\x13AppendBatchResponse\x12%\n" +
	"\x0efirst_sequence\x18\x01 \x01(\x04R\rfirstSequence\x12#\n" +
	"\rnext_sequence\x18\x02 \x01(\x04R\fnextSequence\x12!\n" +
	"\frecord_count\x18\x03 \x01(\rR\vrecordCount\x12F\n" +
	"\x11first_recorded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ffirstRecordedAt\x12D\n" +
	"\x10last_recorded_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastRecordedAt\x123\n" +
	"\x16first_storage_entry_id\x18\x06 \x01(\x04R\x13firstStorageEntryId\x121\n" +
	"\x15last_storage_entry_id\x18\a \x01(\x04R\x12lastStorageEntryId\x12\"\n" +
	"\fdeduplicated\x18\b \x01(\bR\fdeduplicated\x126\n" +
	"\n" +
	"durability\x18\t \x01(\x0e2\x16.streamd.v1.DurabilityR\n" +
	"durability\"\x9f\x01\n" +
	"\vReadRequest\x12-\n" +
	"\x06stream\x18\x01 \x01(\v2\x15.streamd.v1.StreamRefR\x06stream\x12#\n" +
	"\rfrom_sequence\x18\x02 \x01(\x04R\ffromSequence\x12\x1f\n" +
	"\vmax_records\x18\x03 \x01(\rR\n" +
	"maxRecords\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\x04R\bmaxBytes\"\x9b\x01\n" +
	"\fReadResponse\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.streamd.v1.StoredRecordR\arecords\x12#\n" +
	"\rnext_sequence\x18\x02 \x01(\x04R\fnextSequence\x122\n" +
	"\x15current_next_sequence\x18\x03 \x01(\x04R\x13currentNextSequence\"\x84\x02\n" +
	"\x10SubscribeRequest\x12-\n" +
	"\x06stream\x18\x01 \x01(\v2\x15.streamd.v1.StreamRefR\x06stream\x12#\n" +
	"\rfrom_sequence\x18\x02 \x01(\x04R\ffromSequence\x12*\n" +
	"\x11max_batch_records\x18\x03 \x01(\rR\x0fmaxBatchRecords\x12&\n" +
	"\x0fmax_batch_bytes\x18\x04 \x01(\x04R\rmaxBatchBytes\x12H\n" +
	"\x12heartbeat_interval\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\"\xbe\x01\n" +
	"\x11SubscribeResponse\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.streamd.v1.StoredRecordR\arecords\x12#\n" +
	"\rnext_sequence\x18\x02 \x01(\x04R\fnextSequence\x122\n" +
	"\x15current_next_sequence\x18\x03 \x01(\x04R\x13currentNextSequence\x12\x1c\n" +
	"\theartbeat\x18\x04 \x01(\bR\theartbeat\"\xb1\x01\n" +
	"\x12ResolveTimeRequest\x12-\n" +
	"\x06stream\x18\x01 \x01(\v2\x15.streamd.v1.StreamRefR\x06stream\x12;\n" +
	"\vrecorded_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\x12/\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1b.streamd.v1.ResolveTimeModeR\x04mode\"\x91\x01\n" +
	"\x13ResolveTimeResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12H\n" +
	"\x12actual_recorded_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x10actualRecordedAt\"E\n" +
	"\x14InspectStreamRequest\x12-\n" +
	"\x06stream\x18\x01 \x01(\v2\x15.streamd.v1.StreamRefR\x06stream\"\xaa\x02\n" +
	"\x15InspectStreamResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12#\n" +
	"\rhead_sequence\x18\x02 \x01(\x04R\fheadSequence\x12#\n" +
	"\rnext_sequence\x18\x03 \x01(\x04R\fnextSequence\x12!\n" +
	"\frecord_count\x18\x04 \x01(\x04R\vrecordCount\x12F\n" +
	"\x11first_recorded_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0ffirstRecordedAt\x12D\n" +
	"\x10last_recorded_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastRecordedAt\"\x0f\n" +
	"\rHealthRequest\"\x93\x04\n" +
	"\x0eHealthResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.streamd.v1.HealthStatusR\x06status\x12(\n" +
	"\x04role\x18\x02 \x01(\x0e2\x14.streamd.v1.NodeRoleR\x04role\x12\x17\n" +
	"\x04term\x18\x03 \x01(\x04H\x00R\x04term\x88\x01\x01\x126\n" +
	"\n" +
	"durability\x18\x04 \x01(\x0e2\x16.streamd.v1.DurabilityR\n" +
	"durability\x128\n" +
	"\x16local_durable_entry_id\x18\x05 \x01(\x04H\x01R\x13localDurableEntryId\x88\x01\x01\x12+\n" +
	"\x0fcommit_entry_id\x18\x06 \x01(\x04H\x02R\rcommitEntryId\x88\x01\x01\x12-\n" +
	"\x10applied_entry_id\x18\a \x01(\x04H\x03R\x0eappliedEntryId\x88\x01\x01\x12;\n" +
	"\x17replication_lag_entries\x18\b \x01(\x04H\x04R\x15replicationLagEntries\x88\x01\x01\x12\x18\n" +
	"\areasons\x18\t \x03(\tR\areasonsB\a\n" +
	"\x05_termB\x19\n" +
	"\x17_local_durable_entry_idB\x12\n" +
	"\x10_commit_entry_idB\x13\n" +
	"\x11_applied_entry_idB\x1a\n" +
	"\x18_replication_lag_entries\"\x97\x03\n" +
	"\fStreamdError\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.streamd.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12)\n" +
	"\x10result_uncertain\x18\x04 \x01(\bR\x0fresultUncertain\x127\n" +
	"\x15current_next_sequence\x18\x05 \x01(\x04H\x00R\x13currentNextSequence\x88\x01\x01\x12$\n" +
	"\vleader_hint\x18\x06 \x01(\tH\x01R\n" +
	"leaderHint\x88\x01\x01\x12*\n" +
	"\x0erequired_bytes\x18\a \x01(\x04H\x02R\rrequiredBytes\x88\x01\x01\x12\"\n" +
	"\n" +
	"request_id\x18\b \x01(\fH\x03R\trequestId\x88\x01\x01B\x18\n" +
	"\x16_current_next_sequenceB\x0e\n" +
	"\f_leader_hintB\x11\n" +
	"\x0f_required_bytesB\r\n" +
	"\v_request_id*\x8a\x01\n" +
	"\n" +
	"Durability\x12\x1a\n" +
	"\x16DURABILITY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DURABILITY_SINGLE_SYNC\x10\x01\x12 \n" +
	"\x1cDURABILITY_REPLICATED_STRICT\x10\x02\x12\"\n" +
	"\x1eDURABILITY_DEGRADED_LOCAL_ONLY\x10\x03*{\n" +
	"\x0fResolveTimeMode\x12!\n" +
	"\x1dRESOLVE_TIME_MODE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dRESOLVE_TIME_MODE_AT_OR_AFTER\x10\x01\x12\"\n" +
	"\x1eRESOLVE_TIME_MODE_AT_OR_BEFORE\x10\x02*\xbc\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16HEALTH_STATUS_STARTING\x10\x01\x12\x1c\n" +
	"\x18HEALTH_STATUS_READY_READ\x10\x02\x12\x1d\n" +
	"\x19HEALTH_STATUS_READY_WRITE\x10\x03\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x04\x12\x18\n" +
	"\x14HEALTH_STATUS_FAILED\x10\x05*\x83\x01\n" +
	"\bNodeRole\x12\x19\n" +
	"\x15NODE_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NODE_ROLE_SINGLE\x10\x01\x12\x15\n" +
	"\x11NODE_ROLE_PRIMARY\x10\x02\x12\x15\n" +
	"\x11NODE_ROLE_STANDBY\x10\x03\x12\x18\n" +
	"\x14NODE_ROLE_RECOVERING\x10\x04*\xf0\x03\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x02\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x03\x12\x1f\n" +
	"\x1bERROR_CODE_STREAM_NOT_FOUND\x10\x04\x12\x1d\n" +
	"\x19ERROR_CODE_SEQUENCE_AHEAD\x10\x05\x12 \n" +
	"\x1cERROR_CODE_SEQUENCE_CONFLICT\x10\x06\x12\x1f\n" +
	"\x1bERROR_CODE_RECORD_TOO_LARGE\x10\a\x12!\n" +
	"\x1dERROR_CODE_RESOURCE_EXHAUSTED\x10\b\x12%\n" +
	"!ERROR_CODE_DURABILITY_UNAVAILABLE\x10\t\x12\x19\n" +
	"\x15ERROR_CODE_NOT_LEADER\x10\n" +
	"\x12\"\n" +
	"\x1eERROR_CODE_REPLICA_UNAVAILABLE\x10\v\x12 \n" +
	"\x1cERROR_CODE_DEADLINE_EXCEEDED\x10\f\x12\x1c\n" +
	"\x18ERROR_CODE_SLOW_CONSUMER\x10\r\x12\x18\n" +
	"\x14ERROR_CODE_DATA_LOSS\x10\x0e2\x8e\x04\n" +
	"\rStreamService\x12?\n" +
	"\x06Append\x12\x19.streamd.v1.AppendRequest\x1a\x1a.streamd.v1.AppendResponse\x12N\n" +
	"\vAppendBatch\x12\x1e.streamd.v1.AppendBatchRequest\x1a\x1f.streamd.v1.AppendBatchResponse\x129\n" +
	"\x04Read\x12\x17.streamd.v1.ReadRequest\x1a\x18.streamd.v1.ReadResponse\x12J\n" +
	"\tSubscribe\x12\x1c.streamd.v1.SubscribeRequest\x1a\x1d.streamd.v1.SubscribeResponse0\x01\x12N\n" +
	"\vResolveTime\x12\x1e.streamd.v1.ResolveTimeRequest\x1a\x1f.streamd.v1.ResolveTimeResponse\x12T\n" +
	"\rInspectStream\x12 .streamd.v1.InspectStreamRequest\x1a!.streamd.v1.InspectStreamResponse\x12?\n" +
	"\x06Health\x12\x19.streamd.v1.HealthRequest\x1a\x1a.streamd.v1.HealthResponseB2Z0github.com/akzj/streamd/api/streamd/v1;streamdv1b\x06proto3"

var (
	file_streamd_v1_streamd_proto_rawDescOnce sync.Once
	file_streamd_v1_streamd_proto_rawDescData []byte
)

func file_streamd_v1_streamd_proto_rawDescGZIP() []byte {
	file_streamd_v1_streamd_proto_rawDescOnce.Do(func() {
		file_streamd_v1_streamd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streamd_v1_streamd_proto_rawDesc), len(file_streamd_v1_streamd_proto_rawDesc)))
	})
	return file_streamd_v1_streamd_proto_rawDescData
}

var file_streamd_v1_streamd_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_streamd_v1_streamd_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_streamd_v1_streamd_proto_goTypes = []any{
	(Durability)(0),               // 0: streamd.v1.Durability
	(ResolveTimeMode)(0),          // 1: streamd.v1.ResolveTimeMode
	(HealthStatus)(0),             // 2: streamd.v1.HealthStatus
	(NodeRole)(0),                 // 3: streamd.v1.NodeRole
	(ErrorCode)(0),                // 4: streamd.v1.ErrorCode
	(*StreamRef)(nil),             // 5: streamd.v1.StreamRef
	(*InputRecord)(nil),           // 6: streamd.v1.InputRecord
	(*StoredRecord)(nil),          // 7: streamd.v1.StoredRecord
	(*AppendRequest)(nil),         // 8: streamd.v1.AppendRequest
	(*AppendResponse)(nil),        // 9: streamd.v1.AppendResponse
	(*AppendBatchRequest)(nil),    // 10: streamd.v1.AppendBatchRequest
	(*AppendBatchResponse)(nil),   // 11: streamd.v1.AppendBatchResponse
	(*ReadRequest)(nil),           // 12: streamd.v1.ReadRequest
	(*ReadResponse)(nil),          // 13: streamd.v1.ReadResponse
	(*SubscribeRequest)(nil),      // 14: streamd.v1.SubscribeRequest
	(*SubscribeResponse)(nil),     // 15: streamd.v1.SubscribeResponse
	(*ResolveTimeRequest)(nil),    // 16: streamd.v1.ResolveTimeRequest
	(*ResolveTimeResponse)(nil),   // 17: streamd.v1.ResolveTimeResponse
	(*InspectStreamRequest)(nil),  // 18: streamd.v1.InspectStreamRequest
	(*InspectStreamResponse)(nil), // 19: streamd.v1.InspectStreamResponse
	(*HealthRequest)(nil),         // 20: streamd.v1.HealthRequest
	(*HealthResponse)(nil),        // 21: streamd.v1.HealthResponse
	(*StreamdError)(nil),          // 22: streamd.v1.StreamdError
	nil,                           // 23: streamd.v1.InputRecord.HeadersEntry
	nil,                           // 24: streamd.v1.StoredRecord.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 26: google.protobuf.Duration
}
var file_streamd_v1_streamd_proto_depIdxs = []int32{
	23, // 0: streamd.v1.InputRecord.headers:type_name -> streamd.v1.InputRecord.HeadersEntry
	25, // 1: streamd.v1.StoredRecord.recorded_at:type_name -> google.protobuf.Timestamp
	24, // 2: streamd.v1.StoredRecord.headers:type_name -> streamd.v1.StoredRecord.HeadersEntry
	5,  // 3: streamd.v1.AppendRequest.stream:type_name -> streamd.v1.StreamRef
	6,  // 4: streamd.v1.AppendRequest.record:type_name -> streamd.v1.InputRecord
	0,  // 5: streamd.v1.AppendRequest.required_durability:type_name -> streamd.v1.Durability
	25, // 6: streamd.v1.AppendResponse.recorded_at:type_name -> google.protobuf.Timestamp
	0,  // 7: streamd.v1.AppendResponse.durability:type_name -> streamd.v1.Durability
	5,  // 8: streamd.v1.AppendBatchRequest.stream:type_name -> streamd.v1.StreamRef
	6,  // 9: streamd.v1.AppendBatchRequest.records:type_name -> streamd.v1.InputRecord
	0,  // 10: streamd.v1.AppendBatchRequest.required_durability:type_name -> streamd.v1.Durability
	25, // 11: streamd.v1.AppendBatchResponse.first_recorded_at:type_name -> google.protobuf.Timestamp
	25, // 12: streamd.v1.AppendBatchResponse.last_recorded_at:type_name -> google.protobuf.Timestamp
	0,  // 13: streamd.v1.AppendBatchResponse.durability:type_name -> streamd.v1.Durability
	5,  // 14: streamd.v1.ReadRequest.stream:type_name -> streamd.v1.StreamRef
	7,  // 15: streamd.v1.ReadResponse.records:type_name -> streamd.v1.StoredRecord
	5,  // 16: streamd.v1.SubscribeRequest.stream:type_name -> streamd.v1.StreamRef
	26, // 17: streamd.v1.SubscribeRequest.heartbeat_interval:type_name -> google.protobuf.Duration
	7,  // 18: streamd.v1.SubscribeResponse.records:type_name -> streamd.v1.StoredRecord
	5,  // 19: streamd.v1.ResolveTimeRequest.stream:type_name -> streamd.v1.StreamRef
	25, // 20: streamd.v1.ResolveTimeRequest.recorded_at:type_name -> google.protobuf.Timestamp
	1,  // 21: streamd.v1.ResolveTimeRequest.mode:type_name -> streamd.v1.ResolveTimeMode
	25, // 22: streamd.v1.ResolveTimeResponse.actual_recorded_at:type_name -> google.protobuf.Timestamp
	5,  // 23: streamd.v1.InspectStreamRequest.stream:type_name -> streamd.v1.StreamRef
	25, // 24: streamd.v1.InspectStreamResponse.first_recorded_at:type_name -> google.protobuf.Timestamp
	25, // 25: streamd.v1.InspectStreamResponse.last_recorded_at:type_name -> google.protobuf.Timestamp
	2,  // 26: streamd.v1.HealthResponse.status:type_name -> streamd.v1.HealthStatus
	3,  // 27: streamd.v1.HealthResponse.role:type_name -> streamd.v1.NodeRole
	0,  // 28: streamd.v1.HealthResponse.durability:type_name -> streamd.v1.Durability
	4,  // 29: streamd.v1.StreamdError.code:type_name -> streamd.v1.ErrorCode
	8,  // 30: streamd.v1.StreamService.Append:input_type -> streamd.v1.AppendRequest
	10, // 31: streamd.v1.StreamService.AppendBatch:input_type -> streamd.v1.AppendBatchRequest
	12, // 32: streamd.v1.StreamService.Read:input_type -> streamd.v1.ReadRequest
	14, // 33: streamd.v1.StreamService.Subscribe:input_type -> streamd.v1.SubscribeRequest
	16, // 34: streamd.v1.StreamService.ResolveTime:input_type -> streamd.v1.ResolveTimeRequest
	18, // 35: streamd.v1.StreamService.InspectStream:input_type -> streamd.v1.InspectStreamRequest
	20, // 36: streamd.v1.StreamService.Health:input_type -> streamd.v1.HealthRequest
	9,  // 37: streamd.v1.StreamService.Append:output_type -> streamd.v1.AppendResponse
	11, // 38: streamd.v1.StreamService.AppendBatch:output_type -> streamd.v1.AppendBatchResponse
	13, // 39: streamd.v1.StreamService.Read:output_type -> streamd.v1.ReadResponse
	15, // 40: streamd.v1.StreamService.Subscribe:output_type -> streamd.v1.SubscribeResponse
	17, // 41: streamd.v1.StreamService.ResolveTime:output_type -> streamd.v1.ResolveTimeResponse
	19, // 42: streamd.v1.StreamService.InspectStream:output_type -> streamd.v1.InspectStreamResponse
	21, // 43: streamd.v1.StreamService.Health:output_type -> streamd.v1.HealthResponse
	37, // [37:44] is the sub-list for method output_type
	30, // [30:37] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_streamd_v1_streamd_proto_init() }
func file_streamd_v1_streamd_proto_init() {
	if File_streamd_v1_streamd_proto != nil {
		return
	}
	file_streamd_v1_streamd_proto_msgTypes[16].OneofWrappers = []any{}
	file_streamd_v1_streamd_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streamd_v1_streamd_proto_rawDesc), len(file_streamd_v1_streamd_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streamd_v1_streamd_proto_goTypes,
		DependencyIndexes: file_streamd_v1_streamd_proto_depIdxs,
		EnumInfos:         file_streamd_v1_streamd_proto_enumTypes,
		MessageInfos:      file_streamd_v1_streamd_proto_msgTypes,
	}.Build()
	File_streamd_v1_streamd_proto = out.File
	file_streamd_v1_streamd_proto_goTypes = nil
	file_streamd_v1_streamd_proto_depIdxs = nil
}
